name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase owner and set version
        id: meta
        shell: bash
        run: |
          OWNER="${GITHUB_REPOSITORY%%/*}"
          OWNER_LC="$(echo "$OWNER" | tr '[:upper:]' '[:lower:]')"
          echo "owner_lc=$OWNER_LC" >> "$GITHUB_OUTPUT"
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "version=${GITHUB_REF#refs/tags/}" >> "$GITHUB_OUTPUT"
          else
            echo "version=edge" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push (branches -> edge,latest)
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/tictactoe:edge
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/tictactoe:latest

      - name: Build and push (tags -> vX.Y.Z,latest)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/tictactoe:${{ steps.meta.outputs.version }}
            ghcr.io/${{ steps.meta.outputs.owner_lc }}/tictactoe:latest
