name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Derive owner
        id: meta
        run: echo "OWNER=${GITHUB_REPOSITORY%%/*}" >> $GITHUB_OUTPUT

      - name: Build and push (branch)
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.OWNER }}/tictactoe:edge
            ghcr.io/${{ steps.meta.outputs.OWNER }}/tictactoe:latest

      - name: Build and push (tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.OWNER }}/tictactoe:${{ github.ref_name }}
            ghcr.io/${{ steps.meta.outputs.OWNER }}/tictactoe:latest
